# Window settings
window_padding_width 9
dynamic_window_padding yes
decorations full
background_opacity 0.99
startup_mode maximized

# Font settings
font_family JetBrains Mono Nerd Font
bold_font_family JetBrains Mono Nerd Font
italic_font_family JetBrains Mono Nerd Font
font_size 12.0

# Colors
background #1a1d23
foreground #d8dee9

cursor #afafdf
cursor_text_color #1a1d23
cursor_beam_width 2

# Selection colors
selection_background #2d3b55
selection_foreground #d8dee9

# Normal colors (color0 to color7)
color0 #2e3440
color1 #bf616a
color2 #a3be8c
color3 #ebcb8b
color4 #6ba0f8
color5 #b48ead
color6 #88c0d0
color7 #d8dee9

# Bright colors (color8 to color15)
color8  #4c566a
color9  #d06f79
color10 #b1d196
color11 #f0d399
color12 #7c9dd9
color13 #c895bf
color14 #9cd1e1
color15 #eceff4

# Clipboard
copy_to_clipboard yes

# Cursor style
cursor_shape block
cursor_blink yes

map kitty_mod+shift+1 change_font_size all +0.5
map kitty_mod+shift+MINUS         change_font_size all -0.5
map kitty_mod+shift+0             change_font_size all 0
