LOCATION=3
QRCODE_LOCATION=$LOCATION 
Y_AXIS=0
X_AXIS=0
NOTIFICATIONS="false"
NOTIFICATIONS_ICONS="false"
QRCODE_DIR="/tmp/"
WIDTH_FIX_MAIN=1
WIDTH_FIX_STATUS=10
ASCII_OUT="false"
CHANGE_BARS="false"
SIGNAL_STRENGTH_0="0"
SIGNAL_STRENGTH_1="1"
SIGNAL_STRENGTH_2="12"
SIGNAL_STRENGTH_3="123"
SIGNAL_STRENGTH_4="1234"
SELECTION_PREFIX="~"
LANGUAGE="english"
THEME="ronema.rasi"
